### ISSUE TITLE
Unknown error while decoding infon ressource

### ISSUE THREAD

**Issue by sebsau** [arnodelorme/mffmatlabio#3] opened 2019-01-23 09:11 UTC
While trying to import MFF files into EEGLAB, I got the following message: "Unknown error while decoding infon ressource" (see full output below).

The file is nevertheless read. However, I also don't see breaks/discontinuities marked by an event in the data.

I would be very grateful if you could help me with finding out whether this is an issue or not.

-------
Make sure you call this function with the full MFF ressource path name
Signal Block Version Number: 1
Signal Block Data Size: 87252
Signal Block Header size. 308
Number of Signals: 33
Signal Block Samples: 661
Sample Rate: 500
Signal Depth: 32

Optional Header type: 1
Optional Header number of blocks total: 753
Optional Header number of Samples total: 3005450
Optional Header number of Signals: 33

eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
_**Unknown error while decoding infon ressource**_ ; send us your data file.
MFF Version: 3
File's Recording Time: 2018-04-07T14:37:12.272669+05:30
Coordinate acquisition Time: 2007-06-25T16:33:00.000000-08:00
Coordinate acquisition Method: An Average of Many Data Sets
Coordinate Layout Name: HydroCel GSN 32 1.0
EEG checkset note for expert users: Noze direction now set to default +X in EEG.chanlocs and EEG.dipfit.
Importing 2367 events from file Events_ECI TCP-IP 55513.xml...
Importing epoch.xml ressource: 2 data segments
IMPORTANT Warning: cannot import trials of different length
  importing as segmented data (trial/category info will be lost)
eeg_checkset warning: 2/2368 events had out-of-bounds latencies and were removed
eeg_checkset note: value format of event field 'description' made uniform
eeg_checkset note: value format of event field 'begintime' made uniform
eeg_checkset note: value format of event field 'classid' made uniform
eeg_checkset note: value format of event field 'code' made uniform
eeg_checkset note: value format of event field 'label' made uniform
eeg_checkset note: value format of event field 'sourcedevice' made uniform
eeg_checkset note: value format of event field 'mffkeys' made uniform
eeg_checkset note: value format of event field 'mffkey_cel' made uniform
eeg_checkset note: value format of event field 'mffkeysbackup' made uniform
eeg_checkset note: value format of event field 'mffkey_obs' made uniform
eeg_checkset note: value format of event field 'mffkey_pos' made uniform
eeg_checkset note: value format of event field 'mffkey_argu' made uniform
eeg_checkset note: value format of event field 'mffkey_rsp' made uniform
eeg_checkset note: value format of event field 'mffkey_eval' made uniform
eeg_checkset note: value format of event field 'mffkey_rtim' made uniform
eeg_checkset note: value format of event field 'mffkey_trl' made uniform

**Comment by arnodelorme** [comment] 2019-09-20 21:50
Can you share the file?

**Comment by arnodelorme** [comment] 2019-10-11 19:21
Duplicate with issue 1, closing
Duplicate of #1

**Closed by arnodelorme** 2019-10-11 19:21 UTC
