### ISSUE TITLE
pop_mffimport "Not Enough Input Arguments Error"

### ISSUE THREAD

**Issue by travery** [arnodelorme/mffmatlabio#8] opened 2019-09-14 23:28 UTC
We have another issue we can’t figure out.. the file (download with link) contents seem to be intact and it opens normally in Net Station but gives an error (image attached) when loading with MFFmatlabIO.

https://electricalgeodesics.sharefile.com/d-s4497356e238401ea

<img width="415" alt="ErrorImage" src="https://user-images.githubusercontent.com/26609024/64914763-cb889b00-d725-11e9-8041-a88f6a128f1c.png">

**Comment by arnodelorme** [comment] 2019-10-11 19:14
Hi Trey,

Are you using the latest version (from this repository). I have tried on Mac Matlab 2019a and Windows Matlab 2017a and was able to import your file without any problem.

Best wishes,

Arno

**Comment by arnodelorme** [comment] 2019-12-31 22:17
Closing this report for now since I cannot reproduce the problem.

**Closed by arnodelorme** 2019-12-31 22:17 UTC
